# docker stack deploy -c ./timescale-stack.yml homeward_timescale
version: "3.4"

services:          
  kong_api:
    image: "kong:3.1.1-ubuntu"
    restart: always
    ports:
      - 8000:8000 # api
      - 8443:8443 # api ssl
      - 8001:8001 # admin
      - 8444:8444 # admin ssl
    env_file: ./kong.env
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2100M
          
  konga:
    image: pantsel/konga:latest
    restart: always
    depends_on:
      - kong_api
    ports:
      - 1337:1337 #admin
    env_file: ./kong.env
      
      
